### ISSUE TITLE
textlint-rule-proofdict: Lint rules set in yaml file specified in 'dictGlob'  is not working

### ISSUE THREAD

**Issue by RyoheiTaima** [proofdict/proofdict#63]
I set a .textlintrc and hoge.yml like below.

- `.textlintrc`
```
{
    "rules": {
        "@proofdict/proofdict": {
          dicts: [
              {"dictGlob": "./dicts/*.yml"},
              {"dictURL": "https://azu.github.io/proof-dictionary"},
          ]
        },
    }
}
```
- `hoge.yml`
```
id: 01F85EN80BE97D528V75H5QC89
description: ''
expected: HOGE
patterns:
  - /hoge/i
tags: []
specs:
  - from: hoge
    to: HOGE
```

- directory structure
```
sample
|- .textlintrc
|- text.md
∟ dicts
    ∟ hoge.yml
```
---

And, I run `npx textlint .\text.md` to check `text.md` markdown file.  But it raise the error like this => `Cannot read property 'indexOf' of undefined`

- `text.md`
```
hoge
```

error detail
```
TypeError: Cannot read property 'indexOf' of undefined
at C:\Users\taima\Desktop\textlinter_test\text.md
    at Object.isNoun (C:\Users\taima\Desktop\textlinter_test\node_modules\@proofdict\tester\lib\TagFilter.js:11:22)
    at C:\Users\taima\Desktop\textlinter_test\node_modules\@proofdict\tester\lib\proofdict-tester.js:38:40
    at Array.map (<anonymous>)
    at ProofdictTester.splitRuleToEachPattern (C:\Users\taima\Desktop\textlinter_test\node_modules\@proofdict\tester\lib\proofdict-tester.js:37:20)
    at new ProofdictTester (C:\Users\taima\Desktop\textlinter_test\node_modules\@proofdict\tester\lib\proofdict-tester.js:26:25)
    at Object.exports.createTester (C:\Users\taima\Desktop\textlinter_test\node_modules\@proofdict\textlint-rule-proofdict\lib\create-tester.js:21:25)
    at C:\Users\taima\Desktop\textlinter_test\node_modules\@proofdict\textlint-rule-proofdict\lib\textlint-rule-proofdict.js:156:74
    at step (C:\Users\taima\Desktop\textlinter_test\node_modules\@proofdict\textlint-rule-proofdict\lib\textlint-rule-proofdict.js:34:23)
    at Object.next (C:\Users\taima\Desktop\textlinter_test\node_modules\@proofdict\textlint-rule-proofdict\lib\textlint-rule-proofdict.js:15:53)
    at fulfilled (C:\Users\taima\Desktop\textlinter_test\node_modules\@proofdict\textlint-rule-proofdict\lib\textlint-rule-proofdict.js:6:58)
```

**Comment by azu** [comment]
https://github.com/proofdict/proofdict/blob/0df2e88ab5c9dbeb3736255d141beb7d1c5cd93c/packages/%40proofdict/tester/src/TagFilter.ts#L11-L13
fmm, `dict.tags` is undefined.
Probably, the tester fail to load yaml content.

📝 `npx` may affect current working dir.

**Comment by RyoheiTaima** [comment]
I think it failed to load a yaml file. Because the yaml loader 'js-yaml' was passed the invalid value 'filePath'
It looks like that function only accept strings. 

https://github.com/nodeca/js-yaml#api
> load (string [ , options ])
> Parses string as single YAML document. 

```
const yaml = require('js-yaml');
const fs   = require('fs');

// Get document, or throw exception on error
try {
  const doc = yaml.load(fs.readFileSync('/home/ixti/example.yml', 'utf8'));
  console.log(doc);
} catch (e) {
  console.log(e);
}
```

https://github.com/nodeca/js-yaml/blob/ab31bba6b41f58390f431123ffec5031b986edf5/migrate_v3_to_v4.md#safeload-safeloadall-safedump--load-loadall-dump
```
yaml.safeLoad(str)
yaml.safeLoadAll(str)
yaml.safeDump(obj)
```


So, this issue will be resolved by fixing the file `./packages/\@proofdict/textlint-rule-proofdict/lib/fetch-dictionary/node.js
` like below.

```diff
+ var fs = __importStar(require("fs"))
var globby = __importStar(require("globby"));
var js_yaml_1 = __importDefault(require("js-yaml"));
exports.default = (function (options, mode) {
    if (mode !== "LOCAL" /* LOCAL */) {
        return;
    }
    if (!options.dictGlob) {
        return;
    }
    try {
        var files = globby.sync(options.dictGlob);
        return files.map(function (filePath) {
+            return js_yaml_1.default.safeLoad(fs.readFileSync(filePath, "utf8"));
-            return js_yaml_1.default.safeLoad(filePath);
        });
    }
    catch (error) {
        console.error(error);
    }
    return;
});
```
